export const countries_de = [
    { value: "Ägypten", label: "Ägypten" },
    { value: "Äquatorial-Guinea", label: "Äquatorial-Guinea" },
    { value: "Äthiopien", label: "Äthiopien" },
    { value: "Åland-Inseln", label: "Åland-Inseln" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albanien", label: "Albanien" },
    { value: "Algerien", label: "Algerien" },
    { value: "Amerikanisch-Samoa", label: "Amerikanisch-Samoa" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguilla", label: "Anguilla" },
    { value: "Antigua und Barbuda", label: "Antigua und Barbuda" },
    { value: "Argentinien", label: "Argentinien" },
    { value: "Armenien", label: "Armenien" },
    { value: "Aruba", label: "Aruba" },
    { value: "Aserbaidschan", label: "Aserbaidschan" },
    { value: "Australien", label: "Australien" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesch", label: "Bangladesch" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgien", label: "Belgien" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bermuda", label: "Bermuda" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivien", label: "Bolivien" },
    { value: "Bonaire", label: "Bonaire" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brasilien", label: "Brasilien" },
    { value: "Britische Jungferninseln", label: "Britische Jungferninseln" },
    { value: "Britisches Territorium im Indischen Ozean", label: "Britisches Territorium im Indischen Ozean" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgarien", label: "Bulgarien" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cayman Inseln", label: "Cayman Inseln" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Cook Inseln", label: "Cook Inseln" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Curaçao", label: "Curaçao" },
    { value: "Demokratische Republik Kongo", label: "Demokratische Republik Kongo" },
    { value: "Deutschland", label: "Deutschland" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominikanische Republik", label: "Dominikanische Republik" },
    { value: "Dschibuti", label: "Dschibuti" },
    { value: "Dänemark", label: "Dänemark" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Elfenbeinküste", label: "Elfenbeinküste" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estland", label: "Estland" },
    { value: "Falkland-Inseln", label: "Falkland-Inseln" },
    { value: "Fidschi", label: "Fidschi" },
    { value: "Finnland", label: "Finnland" },
    { value: "Frankreich", label: "Frankreich" },
    { value: "Französisch-Guayana", label: "Französisch-Guayana" },
    { value: "Französisch-Polynesien", label: "Französisch-Polynesien" },
    { value: "Französische Süd- und Antarktisgebiete", label: "Französische Süd- und Antarktisgebiete" },
    { value: "Färöer-Inseln", label: "Färöer-Inseln" },
    { value: "Föderierte Staaten von Mikronesien", label: "Föderierte Staaten von Mikronesien" },
    { value: "Gabun", label: "Gabun" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgien", label: "Georgien" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Grenada", label: "Grenada" },
    { value: "Griechenland", label: "Griechenland" },
    { value: "Grönland", label: "Grönland" },
    { value: "Guadeloupe", label: "Guadeloupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Indien", label: "Indien" },
    { value: "Indonesien", label: "Indonesien" },
    { value: "Irak", label: "Irak" },
    { value: "Iran", label: "Iran" },
    { value: "Island", label: "Island" },
    { value: "Isle of Man", label: "Isle of Man" },
    { value: "Israel", label: "Israel" },
    { value: "Italien", label: "Italien" },
    { value: "Jamaika", label: "Jamaika" },
    { value: "Japan", label: "Japan" },
    { value: "Jemen", label: "Jemen" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kambodscha", label: "Kambodscha" },
    { value: "Kamerun", label: "Kamerun" },
    { value: "Kanada", label: "Kanada" },
    { value: "Kap Verde", label: "Kap Verde" },
    { value: "Kasachstan", label: "Kasachstan" },
    { value: "Katar", label: "Katar" },
    { value: "Kenia", label: "Kenia" },
    { value: "Kirgistan", label: "Kirgistan" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kolumbien", label: "Kolumbien" },
    { value: "Komoren", label: "Komoren" },
    { value: "Kokosinseln", label: "Kokosinseln" },
    { value: "Kroatien", label: "Kroatien" },
    { value: "Kuba", label: "Kuba" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Laos", label: "Laos" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Lettland", label: "Lettland" },
    { value: "Libanon", label: "Libanon" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libyen", label: "Libyen" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Litauen", label: "Litauen" },
    { value: "Luxemburg", label: "Luxemburg" },
    { value: "Madagaskar", label: "Madagaskar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Malediven", label: "Malediven" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marokko", label: "Marokko" },
    { value: "Marshall-Inseln", label: "Marshall-Inseln" },
    { value: "Martinique", label: "Martinique" },
    { value: "Mauretanien", label: "Mauretanien" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mayotte", label: "Mayotte" },
    { value: "Mexiko", label: "Mexiko" },
    { value: "Moldawien", label: "Moldawien" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolei", label: "Mongolei" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Mosambik", label: "Mosambik" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Neukaledonien", label: "Neukaledonien" },
    { value: "Neuseeland", label: "Neuseeland" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niederlande", label: "Niederlande" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Niue", label: "Niue" },
    { value: "Nordkorea", label: "Nordkorea" },
    { value: "Norfolk Inseln", label: "Norfolk Inseln" },
    { value: "Norwegen", label: "Norwegen" },
    { value: "Nördlichen Marianen", label: "Nördlichen Marianen" },
    { value: "Österreich", label: "Österreich" },
    { value: "Oman", label: "Oman" },
    { value: "Ost-Timor", label: "Ost-Timor" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palästina", label: "Palästina" },
    { value: "Panama", label: "Panama" },
    { value: "Papua-Neuguinea", label: "Papua-Neuguinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippinen", label: "Philippinen" },
    { value: "Pitcairn-Inseln", label: "Pitcairn-Inseln" },
    { value: "Polen", label: "Polen" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Republik Irland", label: "Republik Irland" },
    { value: "Republik Kongo", label: "Republik Kongo" },
    { value: "Republik Kosovo", label: "Republik Kosovo" },
    { value: "Republik Mazedonien", label: "Republik Mazedonien" },
    { value: "Ruanda", label: "Ruanda" },
    { value: "Rumänien", label: "Rumänien" },
    { value: "Russland", label: "Russland" },
    { value: "Réunion", label: "Réunion" },
    { value: "Saint-Barthélemy", label: "Saint-Barthélemy" },
    { value: "Saint Kitts und Nevis", label: "Saint Kitts und Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Martin", label: "Saint Martin" },
    { value: "Saint Pierre und Miquelon", label: "Saint Pierre und Miquelon" },
    { value: "Saint Vincent und die Grenadinen", label: "Saint Vincent und die Grenadinen" },
    { value: "Salomon-Inseln", label: "Salomon-Inseln" },
    { value: "Sambia", label: "Sambia" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Saudi-Arabien", label: "Saudi-Arabien" },
    { value: "Schweden", label: "Schweden" },
    { value: "Schweiz", label: "Schweiz" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbien", label: "Serbien" },
    { value: "Seychellen", label: "Seychellen" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Simbabwe", label: "Simbabwe" },
    { value: "Singapur", label: "Singapur" },
    { value: "Sint Maarten", label: "Sint Maarten" },
    { value: "Slowakei", label: "Slowakei" },
    { value: "Slowenien", label: "Slowenien" },
    { value: "Somalia", label: "Somalia" },
    { value: "Spanien", label: "Spanien" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Svalbard und Jan Mayen", label: "Svalbard und Jan Mayen" },
    { value: "Swasiland", label: "Swasiland" },
    { value: "Syrien", label: "Syrien" },
    { value: "São Tomé und Príncipe", label: "São Tomé und Príncipe" },
    { value: "Südafrika", label: "Südafrika" },
    { value: "Süd-Georgien", label: "Süd-Georgien" },
    { value: "Südkorea", label: "Südkorea" },
    { value: "Süd-Sudan", label: "Süd-Sudan" },
    { value: "Tadschikistan", label: "Tadschikistan" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tansania", label: "Tansania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Togo", label: "Togo" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad und Tobago", label: "Trinidad und Tobago" },
    { value: "Tschad", label: "Tschad" },
    { value: "Tschechische Republik", label: "Tschechische Republik" },
    { value: "Tunesien", label: "Tunesien" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Turks- und Caicos-Inseln", label: "Turks- und Caicos-Inseln" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Türkei", label: "Türkei" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "Ungarn", label: "Ungarn" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Usbekistan", label: "Usbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vereinigte Arabische Emirate", label: "Vereinigte Arabische Emirate" },
    { value: "Vereinigtes Königreich", label: "Vereinigtes Königreich" },
    { value: "Vereinigte Staaten", label: "Vereinigte Staaten" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Wallis und Futuna", label: "Wallis und Futuna" },
    { value: "Weihnachtsinsel", label: "Weihnachtsinsel" },
    { value: "Western Sahara", label: "Western Sahara" },
    { value: "Zentralafrikanische Republik", label: "Zentralafrikanische Republik" },
    { value: "Zypern", label: "Zypern" },
];

export const countries_en = [
    { value: "Åland Islands", label: "Åland Islands" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "American Samoa", label: "American Samoa" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguilla", label: "Anguilla" },
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Aruba", label: "Aruba" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bermuda", label: "Bermuda" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bonaire", label: "Bonaire" },
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
    { value: "British Virgin Islands", label: "British Virgin Islands" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Cape Verde", label: "Cape Verde" },
    { value: "Cayman Islands", label: "Cayman Islands" },
    { value: "Central African Republic", label: "Central African Republic" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Christmas Island", label: "Christmas Island" },
    { value: "Cocos Islands", label: "Cocos Islands" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Cook Islands", label: "Cook Islands" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Curaçao", label: "Curaçao" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo" },
    { value: "Denmark", label: "Denmark" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "East Timor", label: "East Timor" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Falkland Islands", label: "Falkland Islands" },
    { value: "Faroe Islands", label: "Faroe Islands" },
    { value: "Federated States of Micronesia", label: "Federated States of Micronesia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "French Guiana", label: "French Guiana" },
    { value: "French Polynesia", label: "French Polynesia" },
    { value: "French Southern and Antarctic Lands", label: "French Southern and Antarctic Lands" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Germany", label: "Germany" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Greece", label: "Greece" },
    { value: "Greenland", label: "Greenland" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guadeloupe", label: "Guadeloupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Isle of Man", label: "Isle of Man" },
    { value: "Israel", label: "Israel" },
    { value: "Italy", label: "Italy" },
    { value: "Ivory Coast", label: "Ivory Coast" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japan", label: "Japan" },
    { value: "Jersey", label: "Jersey" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Martinique", label: "Martinique" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mayotte", label: "Mayotte" },
    { value: "Mexico", label: "Mexico" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "New Caledonia", label: "New Caledonia" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Niue", label: "Niue" },
    { value: "Norfolk Island", label: "Norfolk Island" },
    { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
    { value: "North Korea", label: "North Korea" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine", label: "Palestine" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Pitcairn Islands", label: "Pitcairn Islands" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Qatar", label: "Qatar" },
    { value: "Republic of Ireland", label: "Republic of Ireland" },
    { value: "Republic of Kosovo", label: "Republic of Kosovo" },
    { value: "Republic of Macedonia", label: "Republic of Macedonia" },
    { value: "Republic of the Congo", label: "Republic of the Congo" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Réunion", label: "Réunion" },
    { value: "Saint Barthélemy", label: "Saint Barthélemy" },
    { value: "Saint Helena", label: "Saint Helena" },
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Martin", label: "Saint Martin" },
    { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon" },
    { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Sint Maarten", label: "Sint Maarten" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Somalia", label: "Somalia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Georgia", label: "South Georgia" },
    { value: "South Korea", label: "South Korea" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Spain", label: "Spain" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen" },
    { value: "Swaziland", label: "Swaziland" },
    { value: "Sweden", label: "Sweden" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Syria", label: "Syria" },
    { value: "São Tomé and Príncipe", label: "São Tomé and Príncipe" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Togo", label: "Togo" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "United States", label: "United States" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Wallis and Futuna", label: "Wallis and Futuna" },
    { value: "Western Sahara", label: "Western Sahara" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
];

export const countries_es = [
    { value: "Afganistán", label: "Afganistán" },
    { value: "Albania", label: "Albania" },
    { value: "Alemania", label: "Alemania" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguila", label: "Anguila" },
    { value: "Antigua y Barbuda", label: "Antigua y Barbuda" },
    { value: "Arabia Saudita", label: "Arabia Saudita" },
    { value: "Argelia", label: "Argelia" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Aruba", label: "Aruba" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaiyán", label: "Azerbaiyán" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrein", label: "Bahrein" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belice", label: "Belice" },
    { value: "Benin", label: "Benin" },
    { value: "Bermudas", label: "Bermudas" },
    { value: "Bielorrusia", label: "Bielorrusia" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bonaire", label: "Bonaire" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brasil", label: "Brasil" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Bután", label: "Bután" },
    { value: "Bélgica", label: "Bélgica" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Camboya", label: "Camboya" },
    { value: "Camerún", label: "Camerún" },
    { value: "Canadá", label: "Canadá" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Chipre", label: "Chipre" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoras", label: "Comoras" },
    { value: "Corea Del Norte", label: "Corea Del Norte" },
    { value: "Corea Del Sur", label: "Corea Del Sur" },
    { value: "Costa De Marfil", label: "Costa De Marfil" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Croacia", label: "Croacia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Curazao", label: "Curazao" },
    { value: "Dinamarca", label: "Dinamarca" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egipto", label: "Egipto" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Emiratos Árabes Unidos", label: "Emiratos Árabes Unidos" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Eslovaquia", label: "Eslovaquia" },
    { value: "Eslovenia", label: "Eslovenia" },
    { value: "España", label: "España" },
    { value: "Estados federados de Micronesia", label: "Estados federados de Micronesia" },
    { value: "Estados Unidos", label: "Estados Unidos" },
    { value: "Estonia", label: "Estonia" },
    { value: "Etiopía", label: "Etiopía" },
    { value: "Fiji", label: "Fiji" },
    { value: "Filipinas", label: "Filipinas" },
    { value: "Finlandia", label: "Finlandia" },
    { value: "Francia", label: "Francia" },
    { value: "Gabón", label: "Gabón" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Georgia Del Sur", label: "Georgia Del Sur" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Granada", label: "Granada" },
    { value: "Grecia", label: "Grecia" },
    { value: "Groenlandia", label: "Groenlandia" },
    { value: "Guadalupe", label: "Guadalupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guinea Ecuatorial", label: "Guinea Ecuatorial" },
    { value: "Guyana", label: "Guyana" },
    { value: "Guayana Francesa", label: "Guayana Francesa" },
    { value: "Haití", label: "Haití" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Hungría", label: "Hungría" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Irak", label: "Irak" },
    { value: "Irán", label: "Irán" },
    { value: "Isla De La Reunión", label: "Isla De La Reunión" },
    { value: "Isla De Man", label: "Isla De Man" },
    { value: "Isla De Navidad", label: "Isla De Navidad" },
    { value: "Isla De Norfolk", label: "Isla De Norfolk" },
    { value: "Islandia", label: "Islandia" },
    { value: "Islas Caimán", label: "Islas Caimán" },
    { value: "Islas Cocos", label: "Islas Cocos" },
    { value: "Islas Cook", label: "Islas Cook" },
    { value: "Islas Feroe", label: "Islas Feroe" },
    { value: "Islas Malvinas", label: "Islas Malvinas" },
    { value: "Islas Marianas Del Norte", label: "Islas Marianas Del Norte" },
    { value: "Islas Marshall", label: "Islas Marshall" },
    { value: "Islas Pitcairn", label: "Islas Pitcairn" },
    { value: "Islas Salomón", label: "Islas Salomón" },
    { value: "Islas turcas y Caicos", label: "Islas turcas y Caicos" },
    { value: "Islas Vírgenes Británicas", label: "Islas Vírgenes Británicas" },
    { value: "Islas Åland", label: "Islas Åland" },
    { value: "Israel", label: "Israel" },
    { value: "Italia", label: "Italia" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japón", label: "Japón" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazajstán", label: "Kazajstán" },
    { value: "Kenia", label: "Kenia" },
    { value: "Kirguistán", label: "Kirguistán" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Laos", label: "Laos" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Letonia", label: "Letonia" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libia", label: "Libia" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lituania", label: "Lituania" },
    { value: "Luxemburgo", label: "Luxemburgo" },
    { value: "Líbano", label: "Líbano" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malasia", label: "Malasia" },
    { value: "Malawi", label: "Malawi" },
    { value: "Maldivas", label: "Maldivas" },
    { value: "Malta", label: "Malta" },
    { value: "Malí", label: "Malí" },
    { value: "Marruecos", label: "Marruecos" },
    { value: "Martinica", label: "Martinica" },
    { value: "Mauricio", label: "Mauricio" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mayotte", label: "Mayotte" },
    { value: "Moldavia", label: "Moldavia" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "México", label: "México" },
    { value: "Mónaco", label: "Mónaco" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Niue", label: "Niue" },
    { value: "Noruega", label: "Noruega" },
    { value: "Nueva Caledonia", label: "Nueva Caledonia" },
    { value: "Nueva Zelanda", label: "Nueva Zelanda" },
    { value: "Níger", label: "Níger" },
    { value: "Omán", label: "Omán" },
    { value: "Pakistán", label: "Pakistán" },
    { value: "Palau", label: "Palau" },
    { value: "Palestina", label: "Palestina" },
    { value: "Panamá", label: "Panamá" },
    { value: "Papúa Nueva Guinea", label: "Papúa Nueva Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Países bajos", label: "Países bajos" },
    { value: "Perú", label: "Perú" },
    { value: "Polinesia Francesa", label: "Polinesia Francesa" },
    { value: "Polonia", label: "Polonia" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Qatar", label: "Qatar" },
    { value: "Reino Unido", label: "Reino Unido" },
    { value: "República Centroafricana", label: "República Centroafricana" },
    { value: "República Checa", label: "República Checa" },
    { value: "República de Irlanda", label: "República de Irlanda" },
    { value: "República de Kosovo", label: "República de Kosovo" },
    { value: "República del Congo", label: "República del Congo" },
    { value: "República de Macedonia", label: "República de Macedonia" },
    { value: "República democrática del Congo", label: "República democrática del Congo" },
    { value: "República Dominicana", label: "República Dominicana" },
    { value: "Ruanda", label: "Ruanda" },
    { value: "Rumanía", label: "Rumanía" },
    { value: "Rusia", label: "Rusia" },
    { value: "Sahara Occidental", label: "Sahara Occidental" },
    { value: "Saint Kitts y Nevis", label: "Saint Kitts y Nevis" },
    { value: "Saint Pierre y Miquelon", label: "Saint Pierre y Miquelon" },
    { value: "Samoa", label: "Samoa" },
    { value: "Samoa Americana", label: "Samoa Americana" },
    { value: "San Bartolomé", label: "San Bartolomé" },
    { value: "San Marino", label: "San Marino" },
    { value: "San Martin", label: "San Martin" },
    { value: "Santa Lucía", label: "Santa Lucía" },
    { value: "Santo Tomé y Príncipe", label: "Santo Tomé y Príncipe" },
    { value: "San Vicente y las Granadinas", label: "San Vicente y las Granadinas" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leona", label: "Sierra Leona" },
    { value: "Singapur", label: "Singapur" },
    { value: "Sint Maarten", label: "Sint Maarten" },
    { value: "Siria", label: "Siria" },
    { value: "Somalia", label: "Somalia" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudáfrica", label: "Sudáfrica" },
    { value: "Sudán", label: "Sudán" },
    { value: "Sudán Del Sur", label: "Sudán Del Sur" },
    { value: "Suecia", label: "Suecia" },
    { value: "Suiza", label: "Suiza" },
    { value: "Suriname", label: "Suriname" },
    { value: "Svalbard y Jan Mayen", label: "Svalbard y Jan Mayen" },
    { value: "Swazilandia", label: "Swazilandia" },
    { value: "Tailandia", label: "Tailandia" },
    { value: "Taiwán", label: "Taiwán" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Tayikistán", label: "Tayikistán" },
    { value: "Territorio Británico Del Océano Índico", label: "Territorio Británico Del Océano Índico" },
    { value: "Tierras australes y Antárticas francesas", label: "Tierras australes y Antárticas francesas" },
    { value: "Timor Oriental", label: "Timor Oriental" },
    { value: "Togo", label: "Togo" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad y Tobago", label: "Trinidad y Tobago" },
    { value: "Turkmenistán", label: "Turkmenistán" },
    { value: "Turquía", label: "Turquía" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Túnez", label: "Túnez" },
    { value: "Ucrania", label: "Ucrania" },
    { value: "Uganda", label: "Uganda" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistán", label: "Uzbekistán" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Wallis y Futuna", label: "Wallis y Futuna" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
];